---
output:
  md_document:
    variant: markdown_github
---

# Purpose

Purpose of this work folder.

Ideally store a minimum working example data set in data folder.

Add binary files in bin, and closed R functions in code. Human Readable settings files (e.g. csv) should be placed in settings/


```{r}

rm(list = ls()) # Clean your environment:
gc() # garbage collection - It can be useful to call gc after a large object has been removed, as this may prompt R to return memory to the operating system.
library(tidyverse)
list.files('code/', full.names = T, recursive = T) %>% .[grepl('.R', .)] %>% as.list() %>% walk(~source(.))
```


# Question 1:


```{r}
Texevier::create_template_html(directory = "./QUESTION1" , template_name = "COVID")
```


Question 2:

```{r}
Texevier::create_template_html(directory = "./QUESTION2" , template_name = "London_Weather")
```

Question 3:

```{r}
Texevier::create_template(directory = "./QUESTION3" , 
                               template_name = "Tennis")
```


# Question 4


```{r}
Texevier::create_template(directory = "./QUESTION4" , 
                               template_name = "Netflix")
```

